phrase:
  access_token: 6793ef4095e83447bdf7942e0d4eba5738cb28b610b8676543df7ee21156c929
  project_id: 5df19b03ab16070ba2151bab115fd868
  file format: resx
  
  
  push:
    sources:
    - file: ./src/libs/src/folder1/<tag>.resx
      params:
        file_format: resx
        locale_id: dcf0d2dc5d07e34be35f8e6f57842b7c
        tags: folder1
        update_translations: true
    - file: ./src/libs/src/folder2/<tag>.resx
      params:
        file_format: resx
        locale_id: dcf0d2dc5d07e34be35f8e6f57842b7c
        tags: folder2
        update_translations: true
        
        
  pull:
    targets:
    - file: ./src/localization/*_<locale_code>.resx
      params:
        file_format: resx
        locale_id: 834f7a75b9461f07b7d98c50b24242b5
    - file: ./src/localization/*_<locale_code>.resx
      params:
        file_format: resx
        locale_id: 1dfca7b007eb7c230baee2f8a554195f
    - file: ./src/localization/*_<locale_code>.resx
      params:
        file_format: resx
        locale_id: 04de04bd73305ecf5d056a7bb17679ff
