phrase:
  access_token: 9e148e7b677499b6791862abf9164417247bb0c677ee0baffa8f892ae85717da
  project_id: dd2b28ad50b6982be2f1eec90676d926
  file format: yml
  
  
  push:
    sources:
    - file: ./locale/sample.yml
      params:
        file_format: yml
        locale_id: 7ec2f9b134c3929df38287ff66a0071b
        update_translations: true
        
        
  pull:
    targets:
    - file: ./locale/sample-EN.yml
      params:
        file_format: yml
        locale_id: 6ae8eab1e3f719e19e64eee119cf511b



phrase:
  access_token: adb8529ba9bbcc8e060f842b9f231513506514fe8654d50446c7409d33665a4f
  project_id: 1ea679cb9124a1925498f7c20549bd65
  file format: json
  
  
  push:
    sources:
    - file: ./locale/bahoo.json
      params:
        file_format: yml
        locale_id: 984dd15374130c55faf6a5221eb6e3b9
        update_translations: true
        
        
  pull:
    targets:
    - file: ./locale/sample-ES.yml
      params:
        file_format: yml
        locale_id: 5030ee2e310e344eed569c7aafeb75c5
