phrase:
  access_token: 6793ef4095e83447bdf7942e0d4eba5738cb28b610b8676543df7ee21156c929
  project_id: d3186637d8d2ae261f3f0bc5ef603264
  file format: json
  
  
  push:
    sources:
    - file: ./locale/json_for_translation.json
      params:
        file_format: json
        locale_id: fe46c399629f1650d30834a3f206b842
        update_translations: true
        
        
  pull:
    targets:
    - file: ./locale/json_for_translation_ES.json
      params:
        file_format: json
        locale_id: db318624187d237b9128546f3bf45294
