phrase:
  access_token: 6793ef4095e83447bdf7942e0d4eba5738cb28b610b8676543df7ee21156c929
  project_id: 81d7d5da1956690a1a361cffdef29707
  file format: json
  
  
  push:
    sources:
    - file: ./locale/bahoo.json
      params:
        file_format: json
        locale_id: 578ad30b0dfbd87aa64b5d473b601093
        update_translations: true
        
        
  pull:
    targets:
    - file: ./locale/bahoo-ES.json
      params:
        file_format: json
        locale_id: 43d0c8b027909768fd010601e06d2b11
