phrase:
  access_token: 9e148e7b677499b6791862abf9164417247bb0c677ee0baffa8f892ae85717da
  project_id: dd2b28ad50b6982be2f1eec90676d926
  file format: yml
  
  
  push:
    sources:
    - file: ./locale/sample.yml
      params:
        file_format: yml
        locale_id: 7ec2f9b134c3929df38287ff66a0071b
        update_translations: true
        
        
  pull:
    targets:
    - file: ./locale/sample-EN.yml
      params:
        file_format: yml
        locale_id: 6ae8eab1e3f719e19e64eee119cf511b
