phrase:
  access_token: 6793ef4095e83447bdf7942e0d4eba5738cb28b610b8676543df7ee21156c929
  project_id: 5df19b03ab16070ba2151bab115fd868
  file format: json
  
  
  push:
    sources:
    - file: ./locale/json_for_translation.json
      params:
        file_format: json
        locale_id: 1972114bbfa813754f8755d870abbd6b
        update_translations: true
        
        
  pull:
    targets:
    - file: ./locale/json_for_translation_ES.json
      params:
        file_format: json
        locale_id: 04de04bd73305ecf5d056a7bb17679ff
